In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score


In [3]:
# Load the iris dataset
data = pd.read_csv(r'C:\Users\LOQ\Downloads\archive\iris.data.csv', header=None)
data.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# View the first few rows
print(data.head())


   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [5]:
# Features and target
X = data.drop('species', axis=1)
y = data['species']


In [6]:
#train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [7]:
#Train Naïve Bayes Classifier
# Create the model
model = GaussianNB()

# Train the model
model.fit(X_train, y_train)


GaussianNB()

In [8]:
# Make predictions
y_pred = model.predict(X_test)


In [9]:
# Get confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

# Print confusion matrix
print("Confusion Matrix:\n", cm)



Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [15]:
# Extract True Positives, False Positives, False Negatives, and True Negatives
TP = cm[0, 0]  # True Positive
TN = cm[1, 1]  # True Negative
FP = cm[0, 1]  # False Positive
FN = cm[1, 0]  # False Negative

# Print confusion matrix and values
print("Confusion Matrix:")
print(cm)
print(f"True Positive (TP): {TP}")
print(f"False Negative (FN): {FN}")
print(f"False Positive (FP): {FP}")
print(f"True Negative (TN): {TN}")

# Calculate and print Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Calculate and print Error rate
error_rate = 1 - accuracy
print(f"Error Rate: {error_rate * 100:.2f}%")

# Calculate and print Precision
precision = precision_score(y_test, y_pred)
print(f"Precision: {precision * 100:.2f}%")

# Calculate and print Recall
recall = recall_score(y_test, y_pred)
print(f"Recall: {recall * 100:.2f}%")

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
True Positive (TP): 10
False Negative (FN): 0
False Positive (FP): 0
True Negative (TN): 9
Accuracy: 100.00%
Error Rate: 0.00%


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].